project:
  type: website
  output-dir: docs

website:
  title: "Chunkao Wang's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      # - section: "Basics"
        # href: basics-summary.qmd
        # contents:
          # - index.qmd
          # - basics-knitr.qmd
          # - basics-jupyter.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
