project:
  type: website

website:
  title: "LMMQG"
  # navbar:
    # left:
      # - href: index.qmd
        # text: Home
      # - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          # - basics-knitr.qmd
          # - basics-jupyter.qmd
      # - section: "Layout"
        # contents:
          # - layout.qmd
          # - layout-knitr.qmd
          # - layout-jupyter.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



